name: CI/CD to Google Cloud Run and Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: gen-lang-client-0755469978
      REGION: us-central1
      SERVICE_NAME: my-api-service
      JOB_NAME: my-worker-job
      SERVICE_IMAGE: gcr.io/gen-lang-client-0755469978/api-service
      JOB_IMAGE: gcr.io/gen-lang-client-0755469978/worker-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Activate service account (explicit)
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > "${HOME}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
          gcloud config set project $PROJECT_ID

      - name: Check gcloud auth (debug)
        run: gcloud auth list

      - name: Submit Cloud Build for service image
        run: |
          gcloud builds submit --tag $SERVICE_IMAGE --timeout=3600

      - name: Deploy to Cloud Run (service)
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $SERVICE_IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated

      - name: Submit Cloud Build for job image
        run: |
          gcloud builds submit --tag $JOB_IMAGE --timeout=3600
